
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohammadi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    private static final String USERNAME = "root";
    private static final String PASSWORD = ""; // enter the psw
    private static final String URL = "jdbc:mysql://localhost:3306/studentdb";
    Connection sqlConn;
    
    public Main() {
        initComponents();
        try{
            sqlConn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Couldn't connect to the database!", "Error", 2);
        }
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   
        
    
  // update the table
    private void updateTable(){
        try {;
            Statement stmt = sqlConn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM student;");
            
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            
            // delete all rows
            try{
                do{
                model.removeRow(0);
                }while(model.getRowCount()!=0);
            } catch(Exception e){
            }
            
            // add new records from the table
            while (rs.next()){
                int st_id = rs.getInt("st_id");
                String fname = rs.getString("fname");
                String lname = rs.getString("lname");
                String gender = rs.getString("gender");
                String address = rs.getString("address");
                String ph_num = rs.getString("ph_number");
                String math = rs.getString("math");
                String scinece = rs.getString("science");
                String game = rs.getString("game");
                String dbase = rs.getString("dbase");

                Object[] record = {model.getRowCount()+1, st_id, fname, lname, address, gender, ph_num, math, scinece, game, dbase};
                
                // add records to the table
                model.addRow(record);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    // reset the fiels
    private void reset_fields(){
        tf_st_id.setText("");
        tf_fname.setText("");
        tf_lname.setText("");
        tf_ph.setText("");
        tf_add.setText("");
        gender.setSelectedIndex(0);
        math1.setSelectedIndex(0);
        Science.setSelectedIndex(0);
        game.setSelectedIndex(0);
        database.setSelectedIndex(0);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_st_id = new javax.swing.JTextField();
        tf_ph = new javax.swing.JTextField();
        tf_lname = new javax.swing.JTextField();
        tf_fname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_add = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Science = new javax.swing.JComboBox<>();
        game = new javax.swing.JComboBox<>();
        database = new javax.swing.JComboBox<>();
        math1 = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btn_print = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_add_new = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student IMS");
        setBackground(new java.awt.Color(102, 0, 102));
        setForeground(new java.awt.Color(102, 0, 102));
        setName("root"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1095, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1095, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 51, 153), null, new java.awt.Color(255, 51, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Student Management System");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 13, 450, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1020, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 51, 153), null, new java.awt.Color(255, 51, 51)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Student ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Firstname");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 90, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lastname");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Adress");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 90, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Gender");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Gender");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 90, 30));

        tf_st_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(tf_st_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 33, 250, -1));

        tf_ph.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(tf_ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 110, 30));

        tf_lname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(tf_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 93, 250, -1));

        tf_fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(tf_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 63, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Student ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Firstname");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Lastname");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Address");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Gender");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Phone");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 50, 30));

        tf_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(tf_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 120, 250, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 51, 153), null, new java.awt.Color(255, 51, 51)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Game Dev");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 90, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Science");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 60, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Database");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Math");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 30));

        Science.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Science.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes", "Completed" }));
        Science.setToolTipText("");
        Science.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScienceActionPerformed(evt);
            }
        });
        jPanel3.add(Science, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 80, 30));

        game.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        game.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes", "Completed" }));
        game.setToolTipText("");
        game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameActionPerformed(evt);
            }
        });
        jPanel3.add(game, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 80, 30));

        database.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        database.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes", "Completed" }));
        database.setToolTipText("");
        database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseActionPerformed(evt);
            }
        });
        jPanel3.add(database, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 80, 30));

        math1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        math1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes", "Completed" }));
        math1.setToolTipText("");
        math1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                math1ActionPerformed(evt);
            }
        });
        jPanel3.add(math1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 80, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 340, 170));

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        gender.setToolTipText("");
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 360, 380));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 51, 153), null, new java.awt.Color(255, 51, 51)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_print.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        jPanel4.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 130, 40));

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel4.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 130, 40));

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel4.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 130, 40));

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel4.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 130, 40));

        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel4.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 130, 40));

        btn_add_new.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_add_new.setText("Add New");
        btn_add_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_newActionPerformed(evt);
            }
        });
        jPanel4.add(btn_add_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 130, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 1020, 60));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 51, 153), null, new java.awt.Color(255, 51, 51)));

        table.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 153), 1, true));
        table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID", "Fname", "Lname", "Address", "Gender", "Phone", "Math", "Database", "Game D", "Science"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(255, 204, 255));
        table.setRowHeight(20);
        table.setSelectionBackground(new java.awt.Color(255, 102, 102));
        table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowGrid(true);
        table.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableFocusGained(evt);
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableMousePressed(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 650, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScienceActionPerformed

    private void gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameActionPerformed

    private void databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_databaseActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        var answer = javax.swing.JOptionPane.showConfirmDialog(rootPane, "Do You Want to Exit?", "Exit",JOptionPane.YES_NO_OPTION);
        if (answer==0)
            System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void math1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_math1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_math1ActionPerformed

    private void btn_add_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_newActionPerformed

        try {
            // start a connection to the database
            PreparedStatement pst = sqlConn.prepareStatement("INSERT INTO student VALUES(?,?,?,?,?,?,?,?,?,?);");
            pst.setInt(1, Integer.parseInt(tf_st_id.getText()));
            pst.setString(2, tf_fname.getText());
            pst.setString(3, tf_lname.getText());
            pst.setString(4, (String)gender.getSelectedItem());
            pst.setString(5, tf_add.getText());
            pst.setString(6, tf_ph.getText());
            pst.setString(7, (String)math1.getSelectedItem());
            pst.setString(8, (String)Science.getSelectedItem());
            pst.setString(9, (String)game.getSelectedItem());
            pst.setString(10, (String)database.getSelectedItem());
            pst.execute();
            pst.close();
            
            // 
            JOptionPane.showMessageDialog(rootPane, "The Student's Record Added", "Info", 1);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "???????? :)", "Error", 1);
        }
        // update table
        updateTable();
        reset_fields();
    }//GEN-LAST:event_btn_add_newActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset_fields();
        updateTable();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        try{
            table.print(JTable.PrintMode.FIT_WIDTH);
        } catch(Exception e){}    
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            
            // get the current student ID
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            int row = table.getSelectedRow();
            int st_id = Integer.parseInt(model.getValueAt(row, 1).toString());
            
            // start a connection to the database
            PreparedStatement pst = sqlConn.prepareStatement("UPDATE student SET"
                    + " st_id = ?,fname = ?,lname = ?,gender = ?,address = ?,ph_number = ?,"
                    + "math = ?,science = ?,game = ?,dbase = ? "
                    + "WHERE st_id=?;");
            
            pst.setInt(1, Integer.parseInt(tf_st_id.getText()));
            pst.setString(2, tf_fname.getText());
            pst.setString(3, tf_lname.getText());
            pst.setString(4, (String)gender.getSelectedItem());
            pst.setString(5, tf_add.getText());
            pst.setString(6, tf_ph.getText());
            pst.setString(7, (String)math1.getSelectedItem());
            pst.setString(8, (String)Science.getSelectedItem());
            pst.setString(9, (String)game.getSelectedItem());
            pst.setString(10, (String)database.getSelectedItem());
            pst.setInt(11, st_id);
            pst.execute();
            pst.close();
            // 
            JOptionPane.showMessageDialog(rootPane, "The Student's Record Updated!", "Info", 1);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "???????? :)", "Error", 1);
        }
        // update table
        updateTable();
        reset_fields();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void tableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableFocusGained

    }//GEN-LAST:event_tableFocusGained
    
    private void add_to_txtfields(int row){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        tf_st_id.setText(model.getValueAt(row, 1).toString());
        tf_fname.setText(model.getValueAt(row, 2).toString());
        tf_lname.setText(model.getValueAt(row, 3).toString());
        tf_add.setText(model.getValueAt(row, 4).toString());
        gender.setSelectedItem(model.getValueAt(row, 5));
        tf_ph.setText(model.getValueAt(row, 6).toString());
        math1.setSelectedItem(model.getValueAt(row, 7));
        database.setSelectedItem(model.getValueAt(row, 8));
        Science.setSelectedItem(model.getValueAt(row, 10));
        game.setSelectedItem(model.getValueAt(row, 9));
    }
    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        int key_code = evt.getKeyCode();
        
        if (key_code==38){
            if (row!=0)
                row -= 1;}
        
        else if(key_code==40){
            if (row!=table.getRowCount()-1)
                row += 1;}
        
        add_to_txtfields(row);
    }//GEN-LAST:event_tableKeyPressed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        
        int row = table.getSelectedRow();
        add_to_txtfields(row);
    }//GEN-LAST:event_tableMouseClicked

    private void tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMousePressed

    }//GEN-LAST:event_tableMousePressed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
 
        try {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            int row = table.getSelectedRow();
            int st_id = Integer.parseInt(model.getValueAt(row, 1).toString());
            
            PreparedStatement pst = sqlConn.prepareCall("DELETE FROM student WHERE st_id = ?");
            pst.setInt(1, st_id);
            pst.execute();
            pst.close();
            
            JOptionPane.showMessageDialog(rootPane, "Deleted!", "Info", 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "???????? :)", "Error", 1);
        }
        updateTable();
        reset_fields();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        // TODO add your handling code here:
        btn_exit.setForeground(Color.red);
        
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        // TODO add your handling code here:
        btn_exit.setForeground(Color.black);
    }//GEN-LAST:event_btn_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
      
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Science;
    private javax.swing.JButton btn_add_new;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> database;
    private javax.swing.JComboBox<String> game;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> math1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tf_add;
    private javax.swing.JTextField tf_fname;
    private javax.swing.JTextField tf_lname;
    private javax.swing.JTextField tf_ph;
    private javax.swing.JTextField tf_st_id;
    // End of variables declaration//GEN-END:variables
}
